language: java
jdk:
  - openjdk12
before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: build
      script:
    - ./gradlew build --scan -s
    - stage: test
      script:
    - ./gradlew check
#deploy:
#  provider: heroku
#  api-key:
#    secure: $HEROKU_API_KEY