language: java
jdk:
  - openjdk12
before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: test
      script:
    - ./gradlew check
#    - stage: build
#      script:
#    - ./gradlew build
after_success:
- bash <(curl -s https://codecov.io/bash)
#deploy:
#  provider: heroku
#  api-key:
#    secure: $HEROKU_API_KEY